### ISSUE TITLE
Cookies 

### ISSUE THREAD

**Issue by rishantagarwal** [codeforgeek/node-session#1]
Nice tutorial there, but i have a doubt. I fired up 2 windows both logged in into your application. Both stored 2 cookies in their respective browsers. On swapping the cookie values in both the sessions , the users got swapped. 

It doesn't look good to me.  Any ideas about this ?

**Comment by shaikh-shahid** [comment]
That's because of Global variable used in sharing session information. This is basic tutorial. Here is with external session control.

https://github.com/codeforgeek/Nodejs-Session-Using-Redis

**Comment by rishantagarwal** [comment]
OK . thanks.
